# Generated by Django 6.0.6 on 2026-06-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='clock_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
