# Generated by Django 6.0.6 on 2026-06-29 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerecord_clock_out_time'),
        ('employee_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_portal.employee'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='employee_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
